<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../CachedRawFile.cs" Link="CachedRawFile.cs" />
    <Reference Include="ThermoFisher.CommonCore.RawFileReader">
      <HintPath>../../Libs/NetCore/ThermoFisher.CommonCore.RawFileReader.dll</HintPath>
    </Reference>
    <Reference Include="ThermoFisher.CommonCore.Data">
      <HintPath>../../Libs/NetCore/ThermoFisher.CommonCore.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
